In [1]:
from keras.datasets import imdb # Load the data, keeping only 10,000 of the most frequently occuring words
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words = 10000)

In [2]:
print(type([max(sequence) for sequence in train_data]))

# Find the maximum of all max indexes
max([max(sequence) for sequence in train_data])

<class 'list'>


9999

In [3]:
train_data

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [4]:
# Let's quickly decode a review

# step 1: load the dictionary mappings from word to integer index
word_index = imdb.get_word_index()

# step 2: reverse word index to map integer indexes to their respective words
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

# Step 3: decode the review, mapping integer indices to words
#
# indices are off by 3 because 0, 1, and 2 are reserverd indices for "padding", "Start of sequence" and "unknown"
decoded_review = ' '.join([reverse_word_index.get(i-3, '?') for i in train_data[0]])

decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [5]:
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))    # Creates an all zero matrix of shape (len(sequences),10K)
    for i,sequence in enumerate(sequences):
        results[i,sequence] = 1                        # Sets specific indices of results[i] to 1s
    return results

# Vectorize training Data
X_train = vectorize_sequences(train_data)

# Vectorize testing Data
X_test = vectorize_sequences(test_data)

In [6]:
X_test[0]

array([0., 1., 1., ..., 0., 0., 0.])

# VECTORIZE LABLES

In [16]:
class_names = ['negative','positive']

In [7]:
y_train = np.asarray(train_labels).astype('float32')
y_test  = np.asarray(test_labels).astype('float32')

In [8]:
y_test

array([0., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [9]:
from keras import models 
from keras import layers 
model = models.Sequential() 
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu')) 
model.add(layers.Dense(1, activation='sigmoid'))

In [10]:
from keras import optimizers
from keras import losses 
from keras import metrics 
model.compile(optimizer=optimizers.RMSprop(lr=0.001), loss = losses.binary_crossentropy, metrics = [metrics.binary_accuracy])

In [11]:

# Input for Validation
X_val = X_train[:10000]
partial_X_train = X_train[10000:] # Labels for validation 
y_val = y_train[:10000] 
partial_y_train = y_train[10000:]

In [13]:
history = model.fit(partial_X_train, partial_y_train, epochs=10, batch_size=512, validation_data=(X_val, y_val))

Epoch 1/10
30/30 [==============================] - 1s 33ms/step - loss: 0.0760 - binary_accuracy: 0.9795 - val_loss: 0.3393 - val_binary_accuracy: 0.8789
Epoch 2/10
30/30 [==============================] - 1s 30ms/step - loss: 0.0652 - binary_accuracy: 0.9829 - val_loss: 0.3546 - val_binary_accuracy: 0.8786
Epoch 3/10
30/30 [==============================] - 1s 31ms/step - loss: 0.0536 - binary_accuracy: 0.9867 - val_loss: 0.3763 - val_binary_accuracy: 0.8777
Epoch 4/10
30/30 [==============================] - 1s 29ms/step - loss: 0.0441 - binary_accuracy: 0.9909 - val_loss: 0.3987 - val_binary_accuracy: 0.8775
Epoch 5/10
30/30 [==============================] - 1s 29ms/step - loss: 0.0388 - binary_accuracy: 0.9908 - val_loss: 0.4206 - val_binary_accuracy: 0.8720
Epoch 6/10
30/30 [==============================] - 1s 30ms/step - loss: 0.0296 - binary_accuracy: 0.9948 - val_loss: 0.4411 - val_binary_accuracy: 0.8757
Epoch 7/10
30/30 [==============================] - 1s 32ms/step - los

In [21]:
# Making Predictions for testing data np.set_printoptions(suppress=True) 
import numpy as np

result = model.predict(np.expand_dims(X_test[10],axis=0))
print(result,class_names[int(result[0]>0.5)])

1/1 [==============================] - 0s 77ms/step
[[0.9932654]] positive


In [22]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_pred, y_test)
mae

0.1436

In [24]:
new=[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]

In [25]:
new=vectorize_sequences(new)

In [27]:
result1 = model.predict(np.expand_dims(new,axis=0))
print(result1,class_names[int(result[0]>0.5)])

1/1 [==============================] - 0s 76ms/step
[[[0.56623393]
  [0.50607634]
  [0.58161604]
  [0.44663984]
  [0.44310692]
  [0.7038785 ]
  [0.36259097]
  [0.48601788]
  [0.4780071 ]
  [0.5333006 ]
  [0.4448937 ]
  [0.64268583]
  [0.5300351 ]
  [0.49723768]
  [0.5509509 ]
  [0.54616517]
  [0.50228536]
  [0.51123834]
  [0.5181145 ]
  [0.65732217]
  [0.4208461 ]
  [0.44310692]
  [0.42432767]
  [0.50684327]
  [0.46677512]
  [0.44575912]
  [0.521864  ]
  [0.5927835 ]
  [0.5093461 ]
  [0.72593755]
  [0.40569875]
  [0.5181145 ]
  [0.65870106]
  [0.5509509 ]
  [0.4998693 ]
  [0.50684327]
  [0.3870872 ]
  [0.521864  ]
  [0.51262236]
  [0.5200124 ]
  [0.48123908]
  [0.5509509 ]
  [0.4998693 ]
  [0.5519966 ]
  [0.4385519 ]
  [0.5177299 ]
  [0.5328816 ]
  [0.5575095 ]
  [0.5759012 ]
  [0.74394375]
  [0.5509509 ]
  [0.5151417 ]
  [0.46677512]
  [0.44663984]
  [0.5167568 ]
  [0.5183209 ]
  [0.3769946 ]
  [0.52735543]
  [0.50607634]
  [0.58161604]
  [0.5509509 ]
  [0.7175779 ]
  [0.40856895]
  [